### ISSUE TITLE
Release page + Snap case

### ISSUE THREAD

**Issue by ShalokShalom** [AkashaProject/Translations#11]
On your release page is the link to the blog incorrect. You switched 17 with 18 in the URL.

The other issue is that you recommend the closed source service Snap, that is done by a company which drops 2/3 of its projects within a few years once they bring them too less money. Plus, they sell data to other companies.

AppImage is fully open source and already packaged, why not recommending it? 

There are about 10 different cross distro package managers available, why do you choose the only closed source one? 

This comes in line with choosing Electron, so I really think you should overthink your evaluation process, if there is one at all.

**Comment by 42piratas** [comment]
This issue was moved to AkashaProject/akasha-website#3

**Comment by ShalokShalom** [comment]
404

**Comment by 42piratas** [comment]
Hi @ShalokShalom!

First and foremost, I'm sorry for the late reply, and thank you for your feedback.

I've moved the first part of your ticket to the website repo, so the proper team can have a look at it. That repo is private, though, because otherwise we would give a big margin for scams. But as soon as I have an update from the team, I will get back to you here in this issue. 

Regarding your second feedback, I'll share your point with the team and get back to you here in this issue as well as soon as possible.

Again, thanks for your feedback. We appreciate it!

**Comment by 42piratas** [comment]
@ShalokShalom Btw, could you please point out the link for the mentioned "release page"?

**Comment by 42piratas** [comment]
This issue was moved to AkashaProject/PM#1
